import type { Metadata } from "next";
import { HighlightInit } from "@highlight-run/next/client";
import { getHighlightConfiguration } from "@/shared/vendors/highlight/configuration";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <HighlightInit
        projectId={getHighlightConfiguration().NEXT_PUBLIC_HIGHLIGHT_PROJECT_ID}
        serviceName="Next Highlight POC"
        manualStart
      />
      <html lang="en">
        <body>{children}</body>
      </html>
    </>
  );
}
